const mongoose = require('mongoose');

// ─────────────────────────────────────────────────────────────────────────────
// Default band weights.
// These control HOW LIKELY each ceiling band is to be chosen.
// Higher number = chosen more often.  Roughly exponential decay so low
// multipliers dominate in the long run (house edge).
// Admin can override any value via PUT /admin/config.
// ─────────────────────────────────────────────────────────────────────────────
const DEFAULT_BAND_WEIGHTS = {
  extra_low:    28,   // 1.00–1.90  ~22%
  low:          28,   // 1.00–2.00  ~22%
  low_mid:      26,   // 1.00–4.00  ~21%
  mid:          20,   // 1.00–5.00  ~16%
  mid_high:     10,   // 1.00–7.00   ~8%
  high:          6,   // 1.00–15.0   ~5%
  extra_high:    3,   // 1.00–30.0  ~2.4%
  super_high:    2,   // 1.00–50.0  ~1.6%
  extreme:       1.2, // 1.00–90.0   ~1%
  super_extreme: 0.8, // 1.00–150.0 ~0.6%
};

const bandWeightSchema = new mongoose.Schema(
  {
    extra_low: { type: Number, default: DEFAULT_BAND_WEIGHTS.extra_low },
    low: { type: Number, default: DEFAULT_BAND_WEIGHTS.low },
    low_mid: { type: Number, default: DEFAULT_BAND_WEIGHTS.low_mid },
    mid: { type: Number, default: DEFAULT_BAND_WEIGHTS.mid },
    mid_high: { type: Number, default: DEFAULT_BAND_WEIGHTS.mid_high },
    high: { type: Number, default: DEFAULT_BAND_WEIGHTS.high },
    extra_high: { type: Number, default: DEFAULT_BAND_WEIGHTS.extra_high },
    super_high: { type: Number, default: DEFAULT_BAND_WEIGHTS.super_high },
    extreme: { type: Number, default: DEFAULT_BAND_WEIGHTS.extreme },
    super_extreme: { type: Number, default: DEFAULT_BAND_WEIGHTS.super_extreme },
  },
  { _id: false }
);

const gameConfigSchema = new mongoose.Schema(
  {
    // Singleton key — only one document with key "global" will ever exist.
    key: {
      type: String,
      default: 'global',
      unique: true,
      immutable: true,
    },

    // ── Crash mode ───────────────────────────────────────────────────────────
    // "auto"   → crash point generated by crashGenerator.js on every round.
    // "manual" → existing hash / crash-range path (unchanged).
    crash_mode: {
      type: String,
      enum: ['auto', 'manual'],
      default: 'manual',
    },

    // ── Auto-mode tuning ─────────────────────────────────────────────────────
    // rtp_param: long-run return-to-player fraction, e.g. 0.97 = 97% RTP.
    // Scales the intra-band exponential distribution so the expected
    // multiplier (before house edge) is approximately 1 / rtp_param.
    rtp_param: {
      type: Number,
      default: 0.97,
      min: 0.01,
      max: 1.0,
    },

    band_weights: {
      type: bandWeightSchema,
      default: () => ({ ...DEFAULT_BAND_WEIGHTS }),
    },
  },
  {
    timestamps: true,
  }
);

// ─────────────────────────────────────────────────────────────────────────────
// Static helper — always returns the singleton document, creating it with
// defaults if it does not exist yet (upsert pattern).
// ─────────────────────────────────────────────────────────────────────────────
gameConfigSchema.statics.findOrCreate = async function () {
  const existing = await this.findOne({ key: 'global' });
  if (existing) return existing;

  return this.create({
    key: 'global',
    crash_mode: 'manual',
    rtp_param: 0.97,
    band_weights: { ...DEFAULT_BAND_WEIGHTS },
  });
};

const GameConfig = mongoose.model('GameConfig', gameConfigSchema);

module.exports = { GameConfig, DEFAULT_BAND_WEIGHTS };
